# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\x7f\n\tVideoTask\x12\x11\n\tvideo_url\x18\x01 \x01(\t\x12\x15\n\rwatermark_url\x18\x02 \x01(\t\x12\x10\n\x08x_offset\x18\x03 \x01(\x05\x12\x10\n\x08y_offset\x18\x04 \x01(\x05\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x15\n\rcurrent_epoch\x18\x06 \x01(\x05\"-\n\x08Response\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2g\n\x0bTaskService\x12%\n\nunary_task\x12\n.VideoTask\x1a\t.Response\"\x00\x12\x31\n\x12\x62idirectional_task\x12\n.VideoTask\x1a\t.Response\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOTASK']._serialized_start=16
  _globals['_VIDEOTASK']._serialized_end=143
  _globals['_RESPONSE']._serialized_start=145
  _globals['_RESPONSE']._serialized_end=190
  _globals['_TASKSERVICE']._serialized_start=192
  _globals['_TASKSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
